#!/usr/bin/env python3
"""
Script to add all audit questions to the database via API.

Run with: python add_all_questions.py
"""
# ruff: noqa: E501

import json
import re
from typing import Optional
from urllib.error import HTTPError
from urllib.request import Request, urlopen

BASE_URL = "http://localhost:8000"


def generate_key(question_text: str, stage: str) -> str:
    """Generate a unique key from question text."""
    key = question_text.lower()
    key = re.sub(r"[^a-z0-9\s]", "", key)
    key = re.sub(r"\s+", "_", key)
    key = key[:50]
    prefix = stage[:2].lower()
    return f"{prefix}_{key}"


def parse_evidence_types(primary: str, secondary: str) -> list[str]:
    """Parse evidence types from primary and secondary payload columns."""
    types = []
    if primary and primary.strip() and primary.strip() != "-":
        types.append(primary.strip().lower())
    if secondary and secondary.strip() and secondary.strip() != "-":
        types.append(secondary.strip().lower())
    return types


def normalize_page_type(page_type: str) -> str:
    """Normalize page type to match schema."""
    page_type = page_type.lower().strip()
    mapping = {
        "navigation": "homepage",
        "product page": "product",
        "error page": "homepage",
    }
    return mapping.get(page_type, page_type)


questions_data = [
    {
        "stage": "awareness",
        "question_text": "Does the headline tell me exactly what you sell and why I should care?",
        "primary_payload": "DOM",
        "secondary_payload": "Screenshot",
        "tier": 1,
        "severity": 5,
        "category": "Clear Offer and Value Proposition",
        "page_type": "Homepage",
        "fix_intent": "Make the first headline say what you sell and why it matters",
        "specific_example_fix_text": "",
    },
    {
        "stage": "awareness",
        "question_text": "Is a buyer-relevant problem or frustration mentioned in the headline or subheadline?",
        "primary_payload": "Screenshot",
        "secondary_payload": "DOM",
        "tier": 1,
        "severity": 4,
        "category": "Clear Target Audience Fit",
        "page_type": "Homepage",
        "fix_intent": "Add a clear buyer problem statement in the headline or subheadline",
        "specific_example_fix_text": "",
    },
    {
        "stage": "awareness",
        "question_text": "On the homepage, does the main image show the product being used in a relatable, real-world context that reinforces the brand promise?",
        "primary_payload": "Screenshot",
        "secondary_payload": "-",
        "tier": 2,
        "severity": 3,
        "category": "Visuals and Context Support Products",
        "page_type": "Homepage",
        "fix_intent": "Show the product in use so buyers understand it instantly",
        "specific_example_fix_text": "",
    },
    {
        "stage": "awareness",
        "question_text": 'The H1 or H2 contains at least one quantifiable power word (e.g., "Save 30%," "100% Organic," "Results in 7 days").',
        "primary_payload": "DOM",
        "secondary_payload": "-",
        "tier": 2,
        "severity": 2,
        "category": "Clear Offer and Value Proposition",
        "page_type": "Homepage",
        "fix_intent": "Add one specific number or measurable outcome that is safe and true",
        "specific_example_fix_text": "",
    },
    {
        "stage": "awareness",
        "question_text": "The main product benefit or differentiator is clearly stated in the first screen (above the fold)",
        "primary_payload": "Screenshot",
        "secondary_payload": "DOM",
        "tier": 1,
        "severity": 5,
        "category": "Clear Offer and Value Proposition",
        "page_type": "Homepage",
        "fix_intent": "State the main benefit clearly in the first screen",
        "specific_example_fix_text": "",
    },
    {
        "stage": "awareness",
        "question_text": "Above the fold, the visual hierarchy makes the headline and primary CTA the most dominant elements, with no competing blocks that distract from the first click",
        "primary_payload": "Screenshot",
        "secondary_payload": "DOM",
        "tier": 1,
        "severity": 4,
        "category": "Clear Next Step Direction",
        "page_type": "Homepage",
        "fix_intent": "Remove distractions so the headline and main button stand out first",
        "specific_example_fix_text": "",
    },
    {
        "stage": "awareness",
        "question_text": "On the homepage, is the primary CTA the most visually dominant element above the fold?",
        "primary_payload": "Screenshot",
        "secondary_payload": "DOM",
        "tier": 1,
        "severity": 3,
        "category": "Clear Next Step Direction",
        "page_type": "Homepage",
        "fix_intent": "Make the main button more obvious and more prominent",
        "specific_example_fix_text": "",
    },
    {
        "stage": "awareness",
        "question_text": "If a search yields zero results, does it suggest best sellers?",
        "primary_payload": "",
        "secondary_payload": "",
        "tier": 2,
        "severity": 1,
        "category": "Simple and Intuitive Navigation",
        "page_type": "Navigation",
        "fix_intent": "Add a best sellers suggestion when search returns no results",
        "specific_example_fix_text": "",
    },
    {
        "stage": "awareness",
        "question_text": "Does the homepage become usable within 3 seconds, with no major layout shifts or delays?",
        "primary_payload": "Load Timing",
        "secondary_payload": "-",
        "tier": 1,
        "severity": 5,
        "category": "Simple and Intuitive Navigation",
        "page_type": "Homepage",
        "fix_intent": "Improve load speed and remove layout shifts on first load",
        "specific_example_fix_text": "",
    },
    {
        "stage": "awareness",
        "question_text": "If applicable, is a bold risk-reversal (e.g., 'Money-Back Guarantee') prominently visible instead of buried in the footer?",
        "primary_payload": "Screenshot",
        "secondary_payload": "DOM",
        "tier": 2,
        "severity": 3,
        "category": "Clear Offer and Value Proposition",
        "page_type": "Homepage",
        "fix_intent": "Move the guarantee or return promise closer to the first screen",
        "specific_example_fix_text": "",
    },
    {
        "stage": "awareness",
        "question_text": 'An aggregate star rating (e.g., "4.8/5 Stars") or social proof (Used by 5,000+ people) is visible near the top of the home page.',
        "primary_payload": "Screenshot",
        "secondary_payload": "DOM",
        "tier": 1,
        "severity": 4,
        "category": "Clear Offer and Value Proposition",
        "page_type": "Homepage",
        "fix_intent": "Add visible proof near the first screen, close to the main action",
        "specific_example_fix_text": "",
    },
    {
        "stage": "awareness",
        "question_text": "Buyers can quickly find your return policy, privacy policy, and terms and conditions",
        "primary_payload": "DOM",
        "secondary_payload": "-",
        "tier": 2,
        "severity": 2,
        "category": "Simple and Intuitive Navigation",
        "page_type": "Homepage",
        "fix_intent": "Make policy links easy to find from the header or footer",
        "specific_example_fix_text": "",
    },
    {
        "stage": "awareness",
        "question_text": "Do buyers have a clear and easy way to contact the company for questions, comments, concerns, or order information?",
        "primary_payload": "Screenshot",
        "secondary_payload": "DOM",
        "tier": 1,
        "severity": 3,
        "category": "Simple and Intuitive Navigation",
        "page_type": "Homepage",
        "fix_intent": "Add a clear contact path, like email, chat, or contact page link",
        "specific_example_fix_text": "",
    },
    {
        "stage": "awareness",
        "question_text": "The meta description clearly explains what your business does",
        "primary_payload": "Metadata",
        "secondary_payload": "-",
        "tier": 3,
        "severity": 3,
        "category": "Clear Offer and Value Proposition",
        "page_type": "Homepage",
        "fix_intent": "Write a clear meta description that matches what you sell",
        "specific_example_fix_text": "",
    },
    {
        "stage": "awareness",
        "question_text": "The page title includes your brand name so buyers recognize it",
        "primary_payload": "Metadata",
        "secondary_payload": "DOM",
        "tier": 3,
        "severity": 2,
        "category": "Clear Offer and Value Proposition",
        "page_type": "Homepage",
        "fix_intent": "Add the brand name to the page title for recognition",
        "specific_example_fix_text": "",
    },
    {
        "stage": "awareness",
        "question_text": "Does the link preview image match the visual brand identity found in the website's hero section?",
        "primary_payload": "Screenshot",
        "secondary_payload": "Metadata",
        "tier": 3,
        "severity": 1,
        "category": "Visuals and Context Support Products",
        "page_type": "Homepage",
        "fix_intent": "Align the social share preview image with your main brand look",
        "specific_example_fix_text": "",
    },
    {
        "stage": "awareness",
        "question_text": 'A "Quick Add" button is available on all product collection grid images so users don\'t have to load a new page to begin a conversion.',
        "primary_payload": "DOM",
        "secondary_payload": "Screenshot",
        "tier": 2,
        "severity": 4,
        "category": "Clear Next Step Direction",
        "page_type": "Collection",
        "fix_intent": "Add quick add on collections to reduce steps to cart",
        "specific_example_fix_text": "",
    },
    {
        "stage": "awareness",
        "question_text": "Collection pages default to a helpful sort order (Best Sellers, Top Rated, Newest)",
        "primary_payload": "DOM",
        "secondary_payload": "-",
        "tier": 2,
        "severity": 3,
        "category": "Simple and Intuitive Navigation",
        "page_type": "Collection",
        "fix_intent": "Default sorting to best sellers or top rated to reduce decision effort",
        "specific_example_fix_text": "",
    },
    {
        "stage": "awareness",
        "question_text": "Collection page filters are easy to find and use on mobile without covering the screen or hiding options and include a visible results count and clear filter state",
        "primary_payload": "Screenshot",
        "secondary_payload": "DOM",
        "tier": 2,
        "severity": 3,
        "category": "Simple and Intuitive Navigation",
        "page_type": "Collection",
        "fix_intent": "Make filters easy on mobile and show how many results remain",
        "specific_example_fix_text": "",
    },
    {
        "stage": "awareness",
        "question_text": 'Top-level navigation is limited to 7 items or fewer to avoid "choice paralysis."',
        "primary_payload": "DOM",
        "secondary_payload": "Screenshot",
        "tier": 3,
        "severity": 2,
        "category": "Simple and Intuitive Navigation",
        "page_type": "Homepage",
        "fix_intent": "Reduce the top navigation options to the essentials",
        "specific_example_fix_text": "",
    },
    {
        "stage": "awareness",
        "question_text": "A search function (icon or bar) is accessible in the header on both desktop and mobile.",
        "primary_payload": "DOM",
        "secondary_payload": "Screenshot",
        "tier": 2,
        "severity": 2,
        "category": "Simple and Intuitive Navigation",
        "page_type": "Homepage",
        "fix_intent": "Add a clear search entry point in the header",
        "specific_example_fix_text": "",
    },
    {
        "stage": "awareness",
        "question_text": "The CTA button passes WCAG 2.1 AA color contrast ratio of 4.5:1 or higher for accessibility",
        "primary_payload": "Screenshot",
        "secondary_payload": "-",
        "tier": 2,
        "severity": 4,
        "category": "Clear Next Step Direction",
        "page_type": "Homepage",
        "fix_intent": "Improve button text contrast so it is easy to read",
        "specific_example_fix_text": "",
    },
    {
        "stage": "awareness",
        "question_text": 'The "Shop Now" button on mobile is placed within the "Thumb Zone" (center or bottom half of screen).',
        "primary_payload": "Screenshot",
        "secondary_payload": "-",
        "tier": 2,
        "severity": 2,
        "category": "Clear Next Step Direction",
        "page_type": "Homepage",
        "fix_intent": "Place the main action where it is easy to tap on mobile",
        "specific_example_fix_text": "",
    },
    {
        "stage": "awareness",
        "question_text": "The sticky header does not obstruct product content while scrolling on mobile",
        "primary_payload": "Screenshot",
        "secondary_payload": "-",
        "tier": 2,
        "severity": 2,
        "category": "Simple and Intuitive Navigation",
        "page_type": "Collection",
        "fix_intent": "Reduce sticky header height so it does not cover content",
        "specific_example_fix_text": "",
    },
    {
        "stage": "awareness",
        "question_text": "Breadcrumbs are visible on collection and product pages so buyers always know where they are and can move back easily.",
        "primary_payload": "DOM",
        "secondary_payload": "Screenshot",
        "tier": 3,
        "severity": 1,
        "category": "Simple and Intuitive Navigation",
        "page_type": "Collection",
        "fix_intent": "Add breadcrumbs so buyers can navigate back easily",
        "specific_example_fix_text": "",
    },
    {
        "stage": "awareness",
        "question_text": '404 Check: Does the site have a "Continue Shopping" button on its 404 page?',
        "primary_payload": "",
        "secondary_payload": "",
        "tier": 3,
        "severity": 1,
        "category": "Simple and Intuitive Navigation",
        "page_type": "Error Page",
        "fix_intent": "Add a continue shopping button on the 404 page",
        "specific_example_fix_text": "",
    },
    {
        "stage": "consideration",
        "question_text": "Are the product's main function and its biggest benefit clearly stated or implied when a product page loads.",
        "primary_payload": "Screenshot",
        "secondary_payload": "DOM",
        "tier": 1,
        "severity": 5,
        "category": "Clear Use Case For Target Audience",
        "page_type": "Product Page",
        "fix_intent": "State the main benefit clearly as soon as the product page loads",
        "specific_example_fix_text": "",
    },
    {
        "stage": "consideration",
        "question_text": "Is the star rating located immediately above or below the product price or main description?",
        "primary_payload": "",
        "secondary_payload": "",
        "tier": 1,
        "severity": 4,
        "category": "Customer Reviews and Stories",
        "page_type": "Product Page",
        "fix_intent": "Place star rating close to the price and buy button",
        "specific_example_fix_text": "",
    },
    {
        "stage": "consideration",
        "question_text": "Technical details are easy to find in a dedicated section such as accordion tabs or specs, and are not buried inside long paragraphs",
        "primary_payload": "DOM",
        "secondary_payload": "Screenshot",
        "tier": 1,
        "severity": 3,
        "category": "Clear Use Case For Target Audience",
        "page_type": "Product Page",
        "fix_intent": "Make specs easy to find with short sections or tabs",
        "specific_example_fix_text": "",
    },
    {
        "stage": "consideration",
        "question_text": "On the product page, are images aligned with the product's intended real-life use or setting to help users visualize the application?",
        "primary_payload": "Screenshot",
        "secondary_payload": "-",
        "tier": 2,
        "severity": 3,
        "category": "Clear Use Case For Target Audience",
        "page_type": "Product Page",
        "fix_intent": "Use images that show the product in real use so it is easy to picture",
        "specific_example_fix_text": "",
    },
    {
        "stage": "consideration",
        "question_text": "Choosing a color or size visibly updates the product image to reflect the selection.",
        "primary_payload": "Simulated Interaction",
        "secondary_payload": "DOM",
        "tier": 2,
        "severity": 2,
        "category": "Clear Use Case For Target Audience",
        "page_type": "Product Page",
        "fix_intent": "Ensure variant selection clearly updates the product image",
        "specific_example_fix_text": "",
    },
    {
        "stage": "consideration",
        "question_text": "A clear how to use section with steps is visible on the product page.",
        "primary_payload": "DOM",
        "secondary_payload": "Screenshot",
        "tier": 2,
        "severity": 3,
        "category": "Clear Use Case For Target Audience",
        "page_type": "Product Page",
        "fix_intent": "Add a clear how to use section with simple steps",
        "specific_example_fix_text": "",
    },
    {
        "stage": "consideration",
        "question_text": "Are detailed close-up visuals included to highlight product texture, build, or material quality where relevant?",
        "primary_payload": "Screenshot",
        "secondary_payload": "-",
        "tier": 3,
        "severity": 2,
        "category": "Proof Backing Claims Being Made",
        "page_type": "Product Page",
        "fix_intent": "Add close up photos that show texture, finish, or build quality",
        "specific_example_fix_text": "",
    },
    {
        "stage": "consideration",
        "question_text": "The product is shown next to a scale reference or on a model with listed height/size to confirm dimensions.",
        "primary_payload": "Screenshot",
        "secondary_payload": "DOM",
        "tier": 3,
        "severity": 2,
        "category": "Clear Use Case For Target Audience",
        "page_type": "Product Page",
        "fix_intent": "Add a clear size reference so buyers understand dimensions",
        "specific_example_fix_text": "",
    },
    {
        "stage": "consideration",
        "question_text": "A size guide or fit guide is present when the product has sizing or fit risk.",
        "primary_payload": "DOM",
        "secondary_payload": "-",
        "tier": 2,
        "severity": 3,
        "category": "Clear Use Case For Target Audience",
        "page_type": "Product Page",
        "fix_intent": "Add a size guide or fit guidance when sizing risk exists",
        "specific_example_fix_text": "",
    },
    {
        "stage": "consideration",
        "question_text": "The product page uses bullets, large text, or short paragraphs to make key details easy to skim on mobile.",
        "primary_payload": "Screenshot",
        "secondary_payload": "DOM",
        "tier": 1,
        "severity": 4,
        "category": "Clear Use Case For Target Audience",
        "page_type": "Product Page",
        "fix_intent": "Format key details so they are easy to skim on mobile",
        "specific_example_fix_text": "",
    },
    {
        "stage": "consideration",
        "question_text": "Do the customer reviews specifically mention the same benefits or results that are promised in the product description?",
        "primary_payload": "DOM",
        "secondary_payload": "-",
        "tier": 1,
        "severity": 3,
        "category": "Proof Backing Claims Being Made",
        "page_type": "Product Page",
        "fix_intent": "Encourage reviews that mention outcomes tied to the product promise",
        "specific_example_fix_text": "",
    },
    {
        "stage": "consideration",
        "question_text": "General reviews or testimonials are easy to find and visible near the top of the product page.",
        "primary_payload": "DOM",
        "secondary_payload": "Screenshot",
        "tier": 1,
        "severity": 4,
        "category": "Customer Reviews and Stories",
        "page_type": "Product Page",
        "fix_intent": "Make reviews easy to find near the top of the product page",
        "specific_example_fix_text": "",
    },
    {
        "stage": "consideration",
        "question_text": "Collection page product cards show key purchase signals (price, star rating, top benefit) so buyers can choose faster.",
        "primary_payload": "DOM",
        "secondary_payload": "Screenshot",
        "tier": 2,
        "severity": 3,
        "category": "Customer Reviews and Stories",
        "page_type": "Collection",
        "fix_intent": "Show price and rating on collection cards so buyers can choose faster",
        "specific_example_fix_text": "",
    },
    {
        "stage": "consideration",
        "question_text": 'Individual reviews include a "Verified Buyer" badge to objectively distinguish authentic feedback from general comments.',
        "primary_payload": "DOM",
        "secondary_payload": "-",
        "tier": 2,
        "severity": 1,
        "category": "Authority and Credibility Signals",
        "page_type": "Product Page",
        "fix_intent": "Show a verified buyer badge to separate authentic reviews",
        "specific_example_fix_text": "",
    },
    {
        "stage": "consideration",
        "question_text": "A top-rated customer testimonial appears near the price or purchase button.",
        "primary_payload": "DOM",
        "secondary_payload": "Screenshot",
        "tier": 2,
        "severity": 4,
        "category": "Customer Reviews and Stories",
        "page_type": "Product Page",
        "fix_intent": "Highlight one top review close to the price or buy button",
        "specific_example_fix_text": "",
    },
    {
        "stage": "consideration",
        "question_text": "Do reviews make it easy for buyers to find examples from people with similar needs (through photos, review highlights, or clear themes)?",
        "primary_payload": "DOM",
        "secondary_payload": "-",
        "tier": 2,
        "severity": 2,
        "category": "Customer Reviews and Stories",
        "page_type": "Product Page",
        "fix_intent": "Help buyers scan reviews by adding photos, highlights, or themes",
        "specific_example_fix_text": "",
    },
    {
        "stage": "consideration",
        "question_text": "If UGC exists, is the user-generated content (UGC) or real-customer imagery relevant and supporting the product claims, or is it distracting?",
        "primary_payload": "DOM",
        "secondary_payload": "Screenshot",
        "tier": 2,
        "severity": 3,
        "category": "Proof Backing Claims Being Made",
        "page_type": "Product Page",
        "fix_intent": "Keep UGC relevant and supportive of the claims you make",
        "specific_example_fix_text": "",
    },
    {
        "stage": "consideration",
        "question_text": "Does the page clearly describe the 'ideal user' and the specific situation where this product works best?",
        "primary_payload": "Screenshot",
        "secondary_payload": "DOM",
        "tier": 1,
        "severity": 5,
        "category": "Clear Use Case For Target Audience",
        "page_type": "Product Page",
        "fix_intent": "Describe the ideal user and best use case in simple terms",
        "specific_example_fix_text": "",
    },
    {
        "stage": "consideration",
        "question_text": "If applicable, pricing is anchored with clear value context (bundle savings, compare at price, per use value)",
        "primary_payload": "DOM",
        "secondary_payload": "Screenshot",
        "tier": 2,
        "severity": 2,
        "category": "Proof Backing Claims Being Made",
        "page_type": "Product Page",
        "fix_intent": "Anchor pricing with clear value, such as bundle savings or compare at",
        "specific_example_fix_text": "",
    },
    {
        "stage": "consideration",
        "question_text": "Does the main imagery show the specific result or 'after-state' the customer achieves by using the product?",
        "primary_payload": "Screenshot",
        "secondary_payload": "-",
        "tier": 1,
        "severity": 4,
        "category": "Proof Backing Claims Being Made",
        "page_type": "Product Page",
        "fix_intent": "Show the specific result or after state the buyer is aiming for",
        "specific_example_fix_text": "",
    },
    {
        "stage": "consideration",
        "question_text": 'A "Frequently Bought Together" or "Bundle & Save" widget is present to increase Average Order Value (AOV).',
        "primary_payload": "DOM",
        "secondary_payload": "-",
        "tier": 2,
        "severity": 4,
        "category": "Customer Reviews and Stories",
        "page_type": "Product Page",
        "fix_intent": "Add a frequently bought together or bundle widget to increase AOV",
        "specific_example_fix_text": "",
    },
    {
        "stage": "consideration",
        "question_text": "A visual comparison table is present to show the benefits against generic or competitor alternatives.",
        "primary_payload": "Screenshot",
        "secondary_payload": "DOM",
        "tier": 2,
        "severity": 3,
        "category": "Proof Backing Claims Being Made",
        "page_type": "Product Page",
        "fix_intent": "Add a simple comparison table versus alternatives",
        "specific_example_fix_text": "",
    },
    {
        "stage": "consideration",
        "question_text": 'Clear toggles for "Subscribe & Save" or "Quantity Discounts" are included in the product selection area.',
        "primary_payload": "DOM",
        "secondary_payload": "-",
        "tier": 2,
        "severity": 2,
        "category": "Guarantees or Risk Reducers",
        "page_type": "Product Page",
        "fix_intent": "Make subscribe and save and quantity options clear and easy to use",
        "specific_example_fix_text": "",
    },
    {
        "stage": "consideration",
        "question_text": "The page proactively answers buyer questions about fit, sizing, compatibility, or expectations with an FAQ or similar section",
        "primary_payload": "DOM",
        "secondary_payload": "Medium",
        "tier": 1,
        "severity": 4,
        "category": "Authority and Credibility Signals",
        "page_type": "Product Page",
        "fix_intent": "Answer common questions with an FAQ so objections are handled",
        "specific_example_fix_text": "",
    },
    {
        "stage": "conversion",
        "question_text": "After adding to cart, the page clearly confirms success (e.g., animation, mini-cart, or confirmation message).",
        "primary_payload": "Simulated Interaction",
        "secondary_payload": "Screenshot",
        "tier": 3,
        "severity": 5,
        "category": "Frictionless Form and Field Experience",
        "page_type": "Cart",
        "fix_intent": "Add a clear add to cart confirmation so buyers know it worked",
        "specific_example_fix_text": "",
    },
    {
        "stage": "conversion",
        "question_text": "When product quantities are updated in the cart, the subtotal and item count adjust automatically.",
        "primary_payload": "Simulated Interaction",
        "secondary_payload": "DOM",
        "tier": 3,
        "severity": 4,
        "category": "Frictionless Form and Field Experience",
        "page_type": "Cart",
        "fix_intent": "Ensure totals and item counts update instantly when quantity changes",
        "specific_example_fix_text": "",
    },
    {
        "stage": "conversion",
        "question_text": "The main checkout CTA uses language that matches the start of the next page",
        "primary_payload": "Simulated Interaction",
        "secondary_payload": "DOM",
        "tier": 1,
        "severity": 3,
        "category": "Primary Call to Action Strength",
        "page_type": "Cart",
        "fix_intent": "Make the checkout button wording match what buyers see next",
        "specific_example_fix_text": "",
    },
    {
        "stage": "conversion",
        "question_text": 'The mini-cart or cart page offers 1-click "Frequently Bought Together" additions to increase order size before the final checkout.',
        "primary_payload": "DOM",
        "secondary_payload": "-",
        "tier": 1,
        "severity": 5,
        "category": "Pricing and Cost Transparency",
        "page_type": "Cart",
        "fix_intent": "Add simple one click add ons in cart to increase order value",
        "specific_example_fix_text": "",
    },
    {
        "stage": "conversion",
        "question_text": "The main action button is easy to see on all devices and leads logically toward the next step in the checkout",
        "primary_payload": "Screenshot",
        "secondary_payload": "DOM",
        "tier": 2,
        "severity": 4,
        "category": "Primary Call to Action Strength",
        "page_type": "Cart",
        "fix_intent": "Make the main next step button obvious and consistent on all devices",
        "specific_example_fix_text": "",
    },
    {
        "stage": "conversion",
        "question_text": 'The mini-cart shows a spend-based progress message (e.g., "$10 to free shipping") that updates as items are added.',
        "primary_payload": "DOM",
        "secondary_payload": "Simulated Interaction",
        "tier": 2,
        "severity": 3,
        "category": "Pricing and Cost Transparency",
        "page_type": "Cart",
        "fix_intent": "Use a progress message that updates as items are added",
        "specific_example_fix_text": "",
    },
    {
        "stage": "conversion",
        "question_text": "The payment page includes a persistent summary showing product, quantity, and total cost. including shipping",
        "primary_payload": "DOM",
        "secondary_payload": "Screenshot",
        "tier": 2,
        "severity": 2,
        "category": "Pricing and Cost Transparency",
        "page_type": "Cart",
        "fix_intent": "Keep an order summary visible so buyers do not lose context",
        "specific_example_fix_text": "",
    },
    {
        "stage": "conversion",
        "question_text": "All fees (e.g., tax, shipping) are shown before the final checkout screen.",
        "primary_payload": "Simulated Interaction",
        "secondary_payload": "DOM",
        "tier": 1,
        "severity": 5,
        "category": "Pricing and Cost Transparency",
        "page_type": "Checkout",
        "fix_intent": "Show shipping and taxes before the final payment step",
        "specific_example_fix_text": "",
    },
    {
        "stage": "conversion",
        "question_text": "The checkout page loads without delay and is visually stable within 3 seconds.",
        "primary_payload": "Load Timing",
        "secondary_payload": "-",
        "tier": 1,
        "severity": 5,
        "category": "Technical Performance and Reliability",
        "page_type": "Checkout",
        "fix_intent": "Improve checkout load speed and prevent layout shifts",
        "specific_example_fix_text": "",
    },
    {
        "stage": "conversion",
        "question_text": "Can a user reach the shipping info screen without being forced to create a password or 'Sign In'?",
        "primary_payload": "Screenshot",
        "secondary_payload": "DOM",
        "tier": 1,
        "severity": 4,
        "category": "Checkout Process Simplicity",
        "page_type": "Checkout",
        "fix_intent": "Allow buyers to reach shipping without being forced to sign in",
        "specific_example_fix_text": "",
    },
    {
        "stage": "conversion",
        "question_text": 'Express payment buttons (e.g., Apple Pay, ShopPay, Google Pay) are loaded at the top of the checkout to enable "2-click" purchasing.',
        "primary_payload": "DOM",
        "secondary_payload": "-",
        "tier": 2,
        "severity": 3,
        "category": "Checkout Process Simplicity",
        "page_type": "Checkout",
        "fix_intent": "Add express payment options near the top for faster checkout",
        "specific_example_fix_text": "",
    },
    {
        "stage": "conversion",
        "question_text": "Are trust signals like 'Secure Checkout,' lock icons, or payment logos shown near credit card fields?",
        "primary_payload": "Screenshot",
        "secondary_payload": "DOM",
        "tier": 1,
        "severity": 4,
        "category": "Primary Call to Action Strength",
        "page_type": "Checkout",
        "fix_intent": "Add clear payment trust cues near the card fields",
        "specific_example_fix_text": "",
    },
    {
        "stage": "conversion",
        "question_text": "When returning to the site, buyers still see previously added items in their cart.",
        "primary_payload": "Simulated Interaction",
        "secondary_payload": "-",
        "tier": 2,
        "severity": 3,
        "category": "Technical Performance and Reliability",
        "page_type": "Cart",
        "fix_intent": "Keep cart contents saved when buyers return later",
        "specific_example_fix_text": "",
    },
    {
        "stage": "conversion",
        "question_text": "On mobile, the primary checkout button is placed within reach (e.g., bottom half of screen or fixed to bottom).",
        "primary_payload": "Screenshot",
        "secondary_payload": "-",
        "tier": 3,
        "severity": 3,
        "category": "Primary Call to Action Strength",
        "page_type": "Checkout",
        "fix_intent": "Place the main checkout button where it is easy to reach on mobile",
        "specific_example_fix_text": "",
    },
    {
        "stage": "conversion",
        "question_text": "Key checkout buttons stay visible at the top or bottom of the screen while the user is scrolling.",
        "primary_payload": "Screenshot",
        "secondary_payload": "Simulated Interaction",
        "tier": 3,
        "severity": 3,
        "category": "Primary Call to Action Strength",
        "page_type": "Checkout",
        "fix_intent": "Keep key checkout buttons visible while scrolling",
        "specific_example_fix_text": "",
    },
    {
        "stage": "conversion",
        "question_text": "Checkout fields support browser autofill (e.g., address or contact info).",
        "primary_payload": "DOM",
        "secondary_payload": "-",
        "tier": 1,
        "severity": 3,
        "category": "Frictionless Form and Field Experience",
        "page_type": "Checkout",
        "fix_intent": "Enable browser autofill to reduce typing and errors",
        "specific_example_fix_text": "",
    },
    {
        "stage": "conversion",
        "question_text": "Checkout buttons are large enough to tap on mobile without hitting nearby elements.",
        "primary_payload": "Screenshot",
        "secondary_payload": "DOM",
        "tier": 2,
        "severity": 3,
        "category": "Frictionless Form and Field Experience",
        "page_type": "Checkout",
        "fix_intent": "Increase tap targets so buttons are easy to press on mobile",
        "specific_example_fix_text": "",
    },
    {
        "stage": "conversion",
        "question_text": "The checkout page removes the main navigation and other distractions to show only one clear action at a time.",
        "primary_payload": "DOM",
        "secondary_payload": "Screenshot",
        "tier": 2,
        "severity": 2,
        "category": "Checkout Process Simplicity",
        "page_type": "Checkout",
        "fix_intent": "Remove navigation and distractions so checkout stays focused",
        "specific_example_fix_text": "",
    },
    {
        "stage": "conversion",
        "question_text": "If a field is missed, the form shows the error clearly, instantly, and scrolls the user back to the problem area.",
        "primary_payload": "Simulated Interaction",
        "secondary_payload": "DOM",
        "tier": 1,
        "severity": 4,
        "category": "Frictionless Form and Field Experience",
        "page_type": "Checkout",
        "fix_intent": "Show clear errors and jump buyers back to the field that needs fixing",
        "specific_example_fix_text": "",
    },
]


def add_question(question_data: dict) -> Optional[dict]:
    """Add a single question via API."""
    key = generate_key(question_data["question_text"], question_data["stage"])
    evidence_types = parse_evidence_types(
        question_data.get("primary_payload", ""), question_data.get("secondary_payload", "")
    )

    payload = {
        "key": key,
        "stage": question_data["stage"],
        "category": question_data["category"],
        "page_type": normalize_page_type(question_data["page_type"]),
        "narrative_tier": question_data["tier"],
        "baseline_severity": question_data["severity"],
        "question_text": question_data["question_text"],
        "allowed_evidence_types": evidence_types,
        "ruleset_version": "v1",
        "fix_intent": question_data.get("fix_intent", ""),
        "specific_example_fix_text": question_data.get("specific_example_fix_text", ""),
        "pass_criteria": None,
        "fail_criteria": None,
        "notes": None,
    }

    url = f"{BASE_URL}/audits/questions"
    data = json.dumps(payload).encode("utf-8")

    req = Request(url, data=data, headers={"Content-Type": "application/json"}, method="POST")

    try:
        with urlopen(req) as response:
            if response.status == 201:
                result = json.loads(response.read().decode("utf-8"))
                print(f"✅ Added: {key}")
                return result
    except HTTPError as e:
        if e.code == 409:
            print(f"⚠️  Already exists: {key}")
            return None
        else:
            error_body = e.read().decode("utf-8") if e.fp else str(e)
            print(f"❌ Failed to add {key}: {e.code}")
            print(f"   Error: {error_body}")
            return None
    except Exception as e:
        print(f"❌ Error adding {key}: {str(e)}")
        return None


def main():
    """Add all questions to the database."""
    print(f"Adding {len(questions_data)} questions to {BASE_URL}/audits/questions\n")

    success_count = 0
    skipped_count = 0
    error_count = 0

    for question in questions_data:
        result = add_question(question)
        if result:
            success_count += 1
        elif result is None:
            skipped_count += 1
        else:
            error_count += 1

    print(f"\n{'='*50}")
    print("Summary:")
    print(f"  ✅ Successfully added: {success_count}")
    print(f"  ⚠️  Skipped (already exists): {skipped_count}")
    print(f"  ❌ Errors: {error_count}")
    print(f"{'='*50}")


if __name__ == "__main__":
    main()
